# Migration template for 'initial_schema'

"""'initial_schema'

Revision ID: 3fa3405b3e04
Revises: 
Create Date: 2025-11-04 21:07:20.921577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa3405b3e04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_entities',
    sa.Column('lei', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('jurisdiction', sa.String(length=5), nullable=False),
    sa.Column('legal_form', sa.String(length=255), nullable=False),
    sa.Column('registered_as', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bic', sa.String(length=11), nullable=True),
    sa.Column('next_renewal_date', sa.DateTime(), nullable=True),
    sa.Column('registration_status', sa.String(length=20), nullable=False),
    sa.Column('managing_lou', sa.String(length=20), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.CheckConstraint('status IN ("ACTIVE", "INACTIVE", "PENDING")', name='ck_status_values'),
    sa.PrimaryKeyConstraint('lei')
    )
    op.create_index('idx_lei_status', 'legal_entities', ['lei', 'status'], unique=False)
    op.create_table('market_identification_codes',
    sa.Column('mic', sa.String(length=4), nullable=False),
    sa.Column('operating_mic', sa.String(length=4), nullable=False),
    sa.Column('operation_type', sa.Enum('OPRT', 'SGMT', name='mictype'), nullable=False),
    sa.Column('market_name', sa.String(length=500), nullable=False),
    sa.Column('legal_entity_name', sa.String(length=500), nullable=True),
    sa.Column('lei', sa.String(length=20), nullable=True),
    sa.Column('market_category_code', sa.Enum('APPA', 'ATSS', 'CASP', 'DCMS', 'IDQS', 'MLTF', 'NSPD', 'OTFS', 'OTHR', 'RMOS', 'RMKT', 'SEFS', 'SINT', 'TRFS', name='marketcategorycode'), nullable=True),
    sa.Column('acronym', sa.String(length=50), nullable=True),
    sa.Column('iso_country_code', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'SUSPENDED', 'UPDATED', name='micstatus'), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_update_date', sa.DateTime(), nullable=True),
    sa.Column('last_validation_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('data_source_version', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('mic')
    )
    op.create_index('idx_mic_category', 'market_identification_codes', ['market_category_code'], unique=False)
    op.create_index('idx_mic_country', 'market_identification_codes', ['iso_country_code'], unique=False)
    op.create_index('idx_mic_entity_search', 'market_identification_codes', ['legal_entity_name'], unique=False)
    op.create_index('idx_mic_lei', 'market_identification_codes', ['lei'], unique=False)
    op.create_index('idx_mic_name_search', 'market_identification_codes', ['market_name'], unique=False)
    op.create_index('idx_mic_operating_mic', 'market_identification_codes', ['operating_mic'], unique=False)
    op.create_index('idx_mic_status', 'market_identification_codes', ['status'], unique=False)
    op.create_table('entity_addresses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lei', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('address_lines', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['lei'], ['legal_entities.lei'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_registrations',
    sa.Column('lei', sa.String(length=20), nullable=False),
    sa.Column('initial_date', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('next_renewal', sa.DateTime(), nullable=True),
    sa.Column('managing_lou', sa.String(length=20), nullable=True),
    sa.Column('validation_sources', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['lei'], ['legal_entities.lei'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lei')
    )
    op.create_table('entity_relationship_exceptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lei', sa.String(length=20), nullable=False),
    sa.Column('exception_type', sa.String(length=30), nullable=False),
    sa.Column('exception_reason', sa.String(length=500), nullable=False),
    sa.Column('exception_category', sa.String(length=50), nullable=False),
    sa.Column('provided_parent_lei', sa.String(length=20), nullable=True),
    sa.Column('provided_parent_name', sa.String(length=255), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.CheckConstraint("exception_type IN ('DIRECT_PARENT', 'ULTIMATE_PARENT')", name='ck_exception_type_values'),
    sa.ForeignKeyConstraint(['lei'], ['legal_entities.lei'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lei_exception_type', 'entity_relationship_exceptions', ['lei', 'exception_type'], unique=True)
    op.create_table('entity_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_lei', sa.String(length=20), nullable=False),
    sa.Column('child_lei', sa.String(length=20), nullable=False),
    sa.Column('relationship_type', sa.String(length=20), nullable=False),
    sa.Column('relationship_status', sa.String(length=20), nullable=False),
    sa.Column('relationship_period_start', sa.DateTime(), nullable=False),
    sa.Column('relationship_period_end', sa.DateTime(), nullable=True),
    sa.Column('percentage_of_ownership', sa.Integer(), nullable=True),
    sa.Column('qualification_method', sa.String(length=100), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.CheckConstraint('relationship_type IN ("DIRECT", "ULTIMATE")', name='ck_relationship_type_values'),
    sa.ForeignKeyConstraint(['child_lei'], ['legal_entities.lei'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['parent_lei'], ['legal_entities.lei'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_parent_child', 'entity_relationships', ['parent_lei', 'child_lei', 'relationship_type'], unique=True)
    op.create_table('instruments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('instrument_type', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=True),
    sa.Column('short_name', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('cfi_code', sa.String(length=6), nullable=True),
    sa.Column('commodity_derivative_indicator', sa.Boolean(), nullable=True),
    sa.Column('lei_id', sa.String(length=20), nullable=True),
    sa.Column('publication_from_date', sa.DateTime(), nullable=True),
    sa.Column('competent_authority', sa.String(length=10), nullable=True),
    sa.Column('relevant_trading_venue', sa.String(length=100), nullable=True),
    sa.Column('firds_data', sa.JSON(), nullable=True),
    sa.Column('processed_attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lei_id'], ['legal_entities.lei'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    op.create_index('idx_instruments_unified_cfi', 'instruments', ['cfi_code'], unique=False)
    op.create_index('idx_instruments_unified_competent_auth', 'instruments', ['competent_authority'], unique=False)
    op.create_index('idx_instruments_unified_created', 'instruments', ['created_at'], unique=False)
    op.create_index('idx_instruments_unified_currency', 'instruments', ['currency'], unique=False)
    op.create_index('idx_instruments_unified_isin', 'instruments', ['isin'], unique=False)
    op.create_index('idx_instruments_unified_lei', 'instruments', ['lei_id'], unique=False)
    op.create_index('idx_instruments_unified_type', 'instruments', ['instrument_type'], unique=False)
    op.create_table('figi_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('figi', sa.String(length=12), nullable=True),
    sa.Column('composite_figi', sa.String(length=12), nullable=True),
    sa.Column('share_class_figi', sa.String(length=12), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('security_type', sa.String(length=50), nullable=True),
    sa.Column('market_sector', sa.String(length=50), nullable=True),
    sa.Column('security_description', sa.String(length=255), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['isin'], ['instruments.isin'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('figi')
    )
    op.create_table('trading_venues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('instrument_id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=100), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('mic_code', sa.String(length=4), nullable=True),
    sa.Column('first_trade_date', sa.DateTime(), nullable=True),
    sa.Column('termination_date', sa.DateTime(), nullable=True),
    sa.Column('admission_approval_date', sa.DateTime(), nullable=True),
    sa.Column('request_for_admission_date', sa.DateTime(), nullable=True),
    sa.Column('issuer_requested', sa.Boolean(), nullable=True),
    sa.Column('venue_full_name', sa.String(length=500), nullable=True),
    sa.Column('venue_short_name', sa.String(length=200), nullable=True),
    sa.Column('classification_type', sa.String(length=100), nullable=True),
    sa.Column('venue_currency', sa.String(length=3), nullable=True),
    sa.Column('competent_authority', sa.String(length=100), nullable=True),
    sa.Column('relevant_trading_venue', sa.String(length=100), nullable=True),
    sa.Column('publication_from_date', sa.DateTime(), nullable=True),
    sa.Column('venue_attributes', sa.JSON(), nullable=True),
    sa.Column('original_firds_record', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mic_code'], ['market_identification_codes.mic'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trading_venues_unified_dates', 'trading_venues', ['first_trade_date', 'termination_date'], unique=False)
    op.create_index('idx_trading_venues_unified_instrument_id', 'trading_venues', ['instrument_id'], unique=False)
    op.create_index('idx_trading_venues_unified_isin', 'trading_venues', ['isin'], unique=False)
    op.create_index('idx_trading_venues_unified_isin_venue', 'trading_venues', ['isin', 'venue_id'], unique=False)
    op.create_index('idx_trading_venues_unified_mic_code', 'trading_venues', ['mic_code'], unique=False)
    op.create_index('idx_trading_venues_unified_venue_id', 'trading_venues', ['venue_id'], unique=False)
    op.create_table('transparency_calculations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tech_record_id', sa.Integer(), nullable=True),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('liquidity', sa.Boolean(), nullable=True),
    sa.Column('total_transactions_executed', sa.Integer(), nullable=True),
    sa.Column('total_volume_executed', sa.Float(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['isin'], ['instruments.isin'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transparency_dates', 'transparency_calculations', ['from_date', 'to_date'], unique=False)
    op.create_index('idx_transparency_file_type', 'transparency_calculations', ['file_type'], unique=False)
    op.create_index('idx_transparency_isin', 'transparency_calculations', ['isin'], unique=False)
    op.create_index('idx_transparency_tech_id', 'transparency_calculations', ['tech_record_id'], unique=False)
    op.create_table('transparency_thresholds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transparency_id', sa.String(), nullable=False),
    sa.Column('threshold_type', sa.String(), nullable=False),
    sa.Column('amount_value', sa.Float(), nullable=True),
    sa.Column('number_value', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['transparency_id'], ['transparency_calculations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_threshold_transparency_id', 'transparency_thresholds', ['transparency_id'], unique=False)
    op.create_index('idx_threshold_type', 'transparency_thresholds', ['threshold_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_threshold_type', table_name='transparency_thresholds')
    op.drop_index('idx_threshold_transparency_id', table_name='transparency_thresholds')
    op.drop_table('transparency_thresholds')
    op.drop_index('idx_transparency_tech_id', table_name='transparency_calculations')
    op.drop_index('idx_transparency_isin', table_name='transparency_calculations')
    op.drop_index('idx_transparency_file_type', table_name='transparency_calculations')
    op.drop_index('idx_transparency_dates', table_name='transparency_calculations')
    op.drop_table('transparency_calculations')
    op.drop_index('idx_trading_venues_unified_venue_id', table_name='trading_venues')
    op.drop_index('idx_trading_venues_unified_mic_code', table_name='trading_venues')
    op.drop_index('idx_trading_venues_unified_isin_venue', table_name='trading_venues')
    op.drop_index('idx_trading_venues_unified_isin', table_name='trading_venues')
    op.drop_index('idx_trading_venues_unified_instrument_id', table_name='trading_venues')
    op.drop_index('idx_trading_venues_unified_dates', table_name='trading_venues')
    op.drop_table('trading_venues')
    op.drop_table('figi_mappings')
    op.drop_index('idx_instruments_unified_type', table_name='instruments')
    op.drop_index('idx_instruments_unified_lei', table_name='instruments')
    op.drop_index('idx_instruments_unified_isin', table_name='instruments')
    op.drop_index('idx_instruments_unified_currency', table_name='instruments')
    op.drop_index('idx_instruments_unified_created', table_name='instruments')
    op.drop_index('idx_instruments_unified_competent_auth', table_name='instruments')
    op.drop_index('idx_instruments_unified_cfi', table_name='instruments')
    op.drop_table('instruments')
    op.drop_index('idx_parent_child', table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index('idx_lei_exception_type', table_name='entity_relationship_exceptions')
    op.drop_table('entity_relationship_exceptions')
    op.drop_table('entity_registrations')
    op.drop_table('entity_addresses')
    op.drop_index('idx_mic_status', table_name='market_identification_codes')
    op.drop_index('idx_mic_operating_mic', table_name='market_identification_codes')
    op.drop_index('idx_mic_name_search', table_name='market_identification_codes')
    op.drop_index('idx_mic_lei', table_name='market_identification_codes')
    op.drop_index('idx_mic_entity_search', table_name='market_identification_codes')
    op.drop_index('idx_mic_country', table_name='market_identification_codes')
    op.drop_index('idx_mic_category', table_name='market_identification_codes')
    op.drop_table('market_identification_codes')
    op.drop_index('idx_lei_status', table_name='legal_entities')
    op.drop_table('legal_entities')
    # ### end Alembic commands ###