openapi: 3.0.0
info:
  title: MarketDataAPI
  version: 1.0.0
  description: API for financial market data, instrument details, legal entity information,
    and MIC codes
servers:
- url: http://localhost:5000/api/v1
  description: Development server
paths:
  /instruments:
    get:
      tags:
      - instruments
      summary: Retrieves a paginated list of instruments
      parameters:
      - name: type
        in: query
        description: Filter by instrument type
        schema:
          type: string
          example: equity
      - name: currency
        in: query
        description: Filter by currency code
        schema:
          type: string
          example: USD
      - name: page
        in: query
        description: Page number
        schema:
          type: integer
          default: 1
      - name: per_page
        in: query
        description: Records per page
        schema:
          type: integer
          default: 50
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentListResponse'
    post:
      tags:
      - instruments
      summary: Create a new instrument from FIRDS data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstrumentCreateRequest'
      responses:
        '201':
          description: Instrument created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentDetailResponse'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Instrument not found in FIRDS data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    InstrumentCreateRequest:
      type: object
      required:
      - isin
      - type
      properties:
        isin:
          type: string
          description: ISIN code
          example: US0378331005
        type:
          type: string
          description: Instrument type
          example: equity
        cfi_code:
          type: string
          description: CFI code for validation (optional)
          example: ESVUFR
        symbol:
          type: string
          description: Trading symbol (optional)
          example: AAPL
        name:
          type: string
          description: Instrument name (optional)
          example: Apple Inc.
        currency:
          type: string
          description: Trading currency (optional)
          example: USD
        mic_code:
          type: string
          description: Market Identification Code (optional)
          example: XNYS
    InstrumentListResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        data:
          type: array
          items:
            $ref: '#/components/schemas/Instrument'
        meta:
          $ref: '#/components/schemas/PaginationMeta'
    InstrumentDetailResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: Instrument created successfully
        data:
          $ref: '#/components/schemas/Instrument'
    Instrument:
      type: object
      properties:
        id:
          type: integer
          description: Internal instrument ID
        isin:
          type: string
          description: ISIN code
        type:
          type: string
          description: Instrument type
        symbol:
          type: string
          description: Trading symbol
        full_name:
          type: string
          description: Full instrument name
        currency:
          type: string
          description: Trading currency
        cfi_code:
          type: string
          description: CFI code
        mic_code:
          type: string
          description: Market Identification Code
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    PaginationMeta:
      type: object
      properties:
        page:
          type: integer
        per_page:
          type: integer
        total:
          type: integer
    Error:
      type: object
      properties:
        status:
          type: string
          example: error
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
