version: '3.8'

services:
  marketdata-api:
    build: 
      context: .
      target: production
    container_name: marketdata-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///data/marketdata.db
    volumes:
      - ./data:/app/data
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Database service if using PostgreSQL
  # postgres:
  #   image: postgres:15
  #   container_name: marketdata-postgres
  #   environment:
  #     POSTGRES_DB: marketdata
  #     POSTGRES_USER: marketdata
  #     POSTGRES_PASSWORD: your_password_here
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

  # Optional: Redis for caching
  # redis:
  #   image: redis:7-alpine
  #   container_name: marketdata-redis
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: marketdata-network
