# Migration template for add_missing_transparency_thresholds_table

"""add_missing_transparency_thresholds_table

Revision ID: 0b0e19e0468e
Revises: 54d6126b6e73
Create Date: 2025-11-29 14:16:13.813954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b0e19e0468e'
down_revision: Union[str, None] = '54d6126b6e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transparency_thresholds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transparency_id', sa.String(length=36), nullable=False),
    sa.Column('threshold_type', sa.String(length=100), nullable=False),
    sa.Column('amount_value', sa.Float(), nullable=True),
    sa.Column('number_value', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transparency_id'], ['transparency_calculations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_threshold_transparency_id', 'transparency_thresholds', ['transparency_id'], unique=False)
    op.create_index('idx_threshold_type', 'transparency_thresholds', ['threshold_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_threshold_type', table_name='transparency_thresholds')
    op.drop_index('idx_threshold_transparency_id', table_name='transparency_thresholds')
    op.drop_table('transparency_thresholds')
    # ### end Alembic commands ###