# Migration template for remove_entity_relationship_foreign_key_constraints

"""remove_entity_relationship_foreign_key_constraints

Revision ID: 42b243199bb0
Revises: cb1c09412ddc
Create Date: 2025-11-16 15:15:14.390809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b243199bb0'
down_revision: Union[str, None] = 'cb1c09412ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('FK__entity_re__paren__2704CA5F'), 'entity_relationships', type_='foreignkey')
    op.drop_constraint(op.f('FK__entity_re__child__2610A626'), 'entity_relationships', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('FK__entity_re__child__2610A626'), 'entity_relationships', 'legal_entities', ['child_lei'], ['lei'])
    op.create_foreign_key(op.f('FK__entity_re__paren__2704CA5F'), 'entity_relationships', 'legal_entities', ['parent_lei'], ['lei'])
    # ### end Alembic commands ###