# Migration template for Increase_BIC_and_ticker_column_sizes

"""Increase_BIC_and_ticker_column_sizes

Revision ID: 54d6126b6e73
Revises: 42b243199bb0
Create Date: 2025-11-22 16:31:47.728825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54d6126b6e73'
down_revision: Union[str, None] = '42b243199bb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('figi_mappings', 'ticker',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('legal_entities', 'bic',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('legal_entities', 'bic',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('figi_mappings', 'ticker',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    # ### end Alembic commands ###