# Migration template for 'initial_schema'

"""'initial_schema'

Revision ID: 9acd72f0165d
Revises: 
Create Date: 2025-11-16 10:15:01.618333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9acd72f0165d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_relationship_exceptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lei', sa.String(length=20), nullable=False),
    sa.Column('exception_category', sa.String(length=100), nullable=True),
    sa.Column('exception_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('start_node_lei', sa.String(length=20), nullable=False),
    sa.Column('end_node_lei', sa.String(length=20), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('relationship_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('figi_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('figi', sa.String(length=12), nullable=False),
    sa.Column('composite_figi', sa.String(length=12), nullable=True),
    sa.Column('share_class_figi', sa.String(length=12), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('ticker', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('exchange_code', sa.String(length=10), nullable=True),
    sa.Column('mic_code', sa.String(length=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('security_type', sa.String(length=50), nullable=True),
    sa.Column('security_type2', sa.String(length=50), nullable=True),
    sa.Column('security_description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_composite_figi_active', 'figi_mappings', ['composite_figi', 'is_active'], unique=False)
    op.create_index('idx_exchange_ticker', 'figi_mappings', ['exchange_code', 'ticker'], unique=False)
    op.create_index('idx_figi_isin', 'figi_mappings', ['figi', 'isin'], unique=False)
    op.create_index(op.f('ix_figi_mappings_composite_figi'), 'figi_mappings', ['composite_figi'], unique=False)
    op.create_index(op.f('ix_figi_mappings_figi'), 'figi_mappings', ['figi'], unique=False)
    op.create_index(op.f('ix_figi_mappings_isin'), 'figi_mappings', ['isin'], unique=False)
    op.create_index(op.f('ix_figi_mappings_share_class_figi'), 'figi_mappings', ['share_class_figi'], unique=False)
    op.create_table('legal_entities',
    sa.Column('lei', sa.String(length=20), nullable=False),
    sa.Column('legal_name', sa.String(length=500), nullable=True),
    sa.Column('legal_form', sa.String(length=100), nullable=True),
    sa.Column('entity_status', sa.String(length=20), nullable=True),
    sa.Column('entity_expiration_date', sa.DateTime(), nullable=True),
    sa.Column('entity_expiration_reason', sa.String(length=100), nullable=True),
    sa.Column('registration_status', sa.String(length=20), nullable=True),
    sa.Column('next_renewal_date', sa.DateTime(), nullable=True),
    sa.Column('managing_lou', sa.String(length=20), nullable=True),
    sa.Column('validation_sources', sa.String(length=20), nullable=True),
    sa.Column('validation_authority_id', sa.String(length=100), nullable=True),
    sa.Column('validation_authority_entity_id', sa.String(length=100), nullable=True),
    sa.Column('other_entity_names', sa.Text(), nullable=True),
    sa.Column('transliterated_other_entity_names', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('lei')
    )
    op.create_table('market_identification_codes',
    sa.Column('mic', sa.String(length=4), nullable=False),
    sa.Column('market_name', sa.String(length=200), nullable=True),
    sa.Column('market_category_code', sa.String(length=10), nullable=True),
    sa.Column('acronym', sa.String(length=50), nullable=True),
    sa.Column('iso_country_code', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('status_date', sa.DateTime(), nullable=True),
    sa.Column('operating_mic', sa.String(length=4), nullable=True),
    sa.Column('segment_mic', sa.String(length=4), nullable=True),
    sa.Column('legal_entity_name', sa.String(length=200), nullable=True),
    sa.Column('legal_entity_identifier', sa.String(length=20), nullable=True),
    sa.Column('market_type', sa.String(length=50), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('last_update_date', sa.DateTime(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('mic')
    )
    op.create_table('transparency_calculations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('calculation_date', sa.DateTime(), nullable=False),
    sa.Column('is_transparent', sa.Boolean(), nullable=True),
    sa.Column('transparency_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('calculation_method', sa.String(length=50), nullable=True),
    sa.Column('data_sources', sa.Text(), nullable=True),
    sa.Column('fitrs_file_name', sa.String(length=200), nullable=True),
    sa.Column('fitrs_file_date', sa.DateTime(), nullable=True),
    sa.Column('fitrs_record_count', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_duration_ms', sa.String(length=10), nullable=True),
    sa.Column('liquidity_assessment', sa.Text(), nullable=True),
    sa.Column('market_making_assessment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calc_date_status', 'transparency_calculations', ['calculation_date', 'status'], unique=False)
    op.create_index('idx_fitrs_file', 'transparency_calculations', ['fitrs_file_name'], unique=False)
    op.create_index('idx_isin_calc_date', 'transparency_calculations', ['isin', 'calculation_date'], unique=False)
    op.create_index(op.f('ix_transparency_calculations_isin'), 'transparency_calculations', ['isin'], unique=False)
    op.create_table('entity_addresses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lei', sa.String(length=20), nullable=False),
    sa.Column('address_type', sa.String(length=50), nullable=True),
    sa.Column('first_address_line', sa.String(length=300), nullable=True),
    sa.Column('additional_address_line', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lei'], ['legal_entities.lei'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_registrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lei', sa.String(length=20), nullable=False),
    sa.Column('initial_registration_date', sa.DateTime(), nullable=True),
    sa.Column('last_update_date', sa.DateTime(), nullable=True),
    sa.Column('registration_status', sa.String(length=20), nullable=True),
    sa.Column('next_renewal_date', sa.DateTime(), nullable=True),
    sa.Column('managing_lou', sa.String(length=20), nullable=True),
    sa.Column('validation_sources', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lei'], ['legal_entities.lei'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instruments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('instrument_type', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=True),
    sa.Column('short_name', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('cfi_code', sa.String(length=6), nullable=True),
    sa.Column('commodity_derivative_indicator', sa.Boolean(), nullable=True),
    sa.Column('lei_id', sa.String(length=20), nullable=True),
    sa.Column('publication_from_date', sa.DateTime(), nullable=True),
    sa.Column('competent_authority', sa.String(length=10), nullable=True),
    sa.Column('relevant_trading_venue', sa.String(length=100), nullable=True),
    sa.Column('firds_data', sa.Text(), nullable=True),
    sa.Column('processed_attributes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lei_id'], ['legal_entities.lei'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cfi_code', 'instruments', ['cfi_code'], unique=False)
    op.create_index('idx_competent_authority', 'instruments', ['competent_authority'], unique=False)
    op.create_index('idx_currency', 'instruments', ['currency'], unique=False)
    op.create_index('idx_isin_type', 'instruments', ['isin', 'instrument_type'], unique=False)
    op.create_index(op.f('ix_instruments_instrument_type'), 'instruments', ['instrument_type'], unique=False)
    op.create_index(op.f('ix_instruments_isin'), 'instruments', ['isin'], unique=False)
    op.create_table('trading_venues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('instrument_id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=100), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('mic_code', sa.String(length=4), nullable=True),
    sa.Column('first_trade_date', sa.DateTime(), nullable=True),
    sa.Column('termination_date', sa.DateTime(), nullable=True),
    sa.Column('admission_approval_date', sa.DateTime(), nullable=True),
    sa.Column('request_for_admission_date', sa.DateTime(), nullable=True),
    sa.Column('issuer_requested', sa.Boolean(), nullable=True),
    sa.Column('venue_full_name', sa.String(length=500), nullable=True),
    sa.Column('venue_short_name', sa.String(length=200), nullable=True),
    sa.Column('classification_type', sa.String(length=100), nullable=True),
    sa.Column('venue_currency', sa.String(length=3), nullable=True),
    sa.Column('competent_authority', sa.String(length=100), nullable=True),
    sa.Column('relevant_trading_venue', sa.String(length=100), nullable=True),
    sa.Column('publication_from_date', sa.DateTime(), nullable=True),
    sa.Column('venue_attributes', sa.Text(), nullable=True),
    sa.Column('original_firds_record', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mic_code'], ['market_identification_codes.mic'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trading_venues_dates', 'trading_venues', ['first_trade_date', 'termination_date'], unique=False)
    op.create_index('idx_trading_venues_instrument_id', 'trading_venues', ['instrument_id'], unique=False)
    op.create_index('idx_trading_venues_isin', 'trading_venues', ['isin'], unique=False)
    op.create_index('idx_trading_venues_isin_venue', 'trading_venues', ['isin', 'venue_id'], unique=False)
    op.create_index('idx_trading_venues_mic_code', 'trading_venues', ['mic_code'], unique=False)
    op.create_index('idx_trading_venues_venue_id', 'trading_venues', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trading_venues_venue_id', table_name='trading_venues')
    op.drop_index('idx_trading_venues_mic_code', table_name='trading_venues')
    op.drop_index('idx_trading_venues_isin_venue', table_name='trading_venues')
    op.drop_index('idx_trading_venues_isin', table_name='trading_venues')
    op.drop_index('idx_trading_venues_instrument_id', table_name='trading_venues')
    op.drop_index('idx_trading_venues_dates', table_name='trading_venues')
    op.drop_table('trading_venues')
    op.drop_index(op.f('ix_instruments_isin'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_instrument_type'), table_name='instruments')
    op.drop_index('idx_isin_type', table_name='instruments')
    op.drop_index('idx_currency', table_name='instruments')
    op.drop_index('idx_competent_authority', table_name='instruments')
    op.drop_index('idx_cfi_code', table_name='instruments')
    op.drop_table('instruments')
    op.drop_table('entity_registrations')
    op.drop_table('entity_addresses')
    op.drop_index(op.f('ix_transparency_calculations_isin'), table_name='transparency_calculations')
    op.drop_index('idx_isin_calc_date', table_name='transparency_calculations')
    op.drop_index('idx_fitrs_file', table_name='transparency_calculations')
    op.drop_index('idx_calc_date_status', table_name='transparency_calculations')
    op.drop_table('transparency_calculations')
    op.drop_table('market_identification_codes')
    op.drop_table('legal_entities')
    op.drop_index(op.f('ix_figi_mappings_share_class_figi'), table_name='figi_mappings')
    op.drop_index(op.f('ix_figi_mappings_isin'), table_name='figi_mappings')
    op.drop_index(op.f('ix_figi_mappings_figi'), table_name='figi_mappings')
    op.drop_index(op.f('ix_figi_mappings_composite_figi'), table_name='figi_mappings')
    op.drop_index('idx_figi_isin', table_name='figi_mappings')
    op.drop_index('idx_exchange_ticker', table_name='figi_mappings')
    op.drop_index('idx_composite_figi_active', table_name='figi_mappings')
    op.drop_table('figi_mappings')
    op.drop_table('entity_relationships')
    op.drop_table('entity_relationship_exceptions')
    # ### end Alembic commands ###