# Migration template for remove_lei_foreign_key_constraint_v2

"""remove_lei_foreign_key_constraint_v2

Revision ID: cb1c09412ddc
Revises: 9acd72f0165d
Create Date: 2025-11-16 15:01:25.135992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1c09412ddc'
down_revision: Union[str, None] = '9acd72f0165d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('FK__instrumen__lei_i__18B6AB08'), 'instruments', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('FK__instrumen__lei_i__18B6AB08'), 'instruments', 'legal_entities', ['lei_id'], ['lei'], ondelete='SET NULL')
    # ### end Alembic commands ###