"""update_mic_enums

Revision ID: 8bb128ae650d
Revises: add_mic_support
Create Date: 2025-09-07 15:28:24.095398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '8bb128ae650d'
down_revision = 'add_mic_support'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('firds_e')
    op.drop_table('debts')
    op.drop_table('equities')
    op.drop_table('firds_d')
    op.drop_table('isin_figi_map')
    op.drop_table('futures')
    op.drop_index('idx_related_isins_isin', table_name='related_isins')
    op.drop_index('idx_related_isins_primary_instrument', table_name='related_isins')
    op.drop_index('idx_related_isins_type', table_name='related_isins')
    op.drop_table('related_isins')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_isins',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('primary_instrument_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('related_isin', sa.VARCHAR(length=12), nullable=False),
    sa.Column('sequence_number', sa.INTEGER(), nullable=False),
    sa.Column('relationship_type', sa.VARCHAR(length=9), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['primary_instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_related_isins_type', 'related_isins', ['relationship_type'], unique=False)
    op.create_index('idx_related_isins_primary_instrument', 'related_isins', ['primary_instrument_id'], unique=False)
    op.create_index('idx_related_isins_isin', 'related_isins', ['related_isin'], unique=False)
    op.create_table('futures',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('admission_approval_date', sa.DATE(), nullable=True),
    sa.Column('admission_request_date', sa.DATE(), nullable=True),
    sa.Column('expiration_date', sa.DATE(), nullable=True),
    sa.Column('final_settlement_date', sa.DATE(), nullable=True),
    sa.Column('delivery_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('settlement_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('contract_size', sa.FLOAT(), nullable=True),
    sa.Column('contract_unit', sa.VARCHAR(length=20), nullable=True),
    sa.Column('price_multiplier', sa.FLOAT(), nullable=True),
    sa.Column('settlement_currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('contract_details', sqlite.JSON(), nullable=True),
    sa.Column('final_price_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('underlying_index_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('underlying_single_isin', sa.VARCHAR(length=12), nullable=True),
    sa.Column('basket_isin', sa.VARCHAR(length=12), nullable=True),
    sa.Column('underlying_index_isin', sa.VARCHAR(length=12), nullable=True),
    sa.Column('underlying_single_index_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('underlying_single_lei', sa.VARCHAR(length=20), nullable=True),
    sa.Column('basket_lei', sa.VARCHAR(length=20), nullable=True),
    sa.Column('additional_metal_product', sa.VARCHAR(length=100), nullable=True),
    sa.Column('oil_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('sub_product', sa.VARCHAR(length=100), nullable=True),
    sa.Column('additional_sub_product', sa.VARCHAR(length=100), nullable=True),
    sa.Column('metal_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('precious_metal', sa.VARCHAR(length=50), nullable=True),
    sa.Column('multi_commodity_base_product', sa.VARCHAR(length=100), nullable=True),
    sa.Column('other_c10_nondeliverable_base_product', sa.VARCHAR(length=100), nullable=True),
    sa.Column('other_c10_nondeliverable_sub_product', sa.VARCHAR(length=100), nullable=True),
    sa.Column('underlying_index_name_term_unit', sa.VARCHAR(length=10), nullable=True),
    sa.Column('underlying_index_name_term_value', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('isin_figi_map',
    sa.Column('ISIN', sa.TEXT(), nullable=True),
    sa.Column('FIGI', sa.TEXT(), nullable=True),
    sa.Column('CompositeFIGI', sa.TEXT(), nullable=True),
    sa.Column('ShareClassFIGI', sa.TEXT(), nullable=True),
    sa.Column('Ticker', sa.TEXT(), nullable=True),
    sa.Column('SecurityType', sa.TEXT(), nullable=True),
    sa.Column('MarketSector', sa.TEXT(), nullable=True),
    sa.Column('SecurityDescription', sa.TEXT(), nullable=True),
    sa.Column('LastUpdated', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ISIN'], ['firds_e.ISIN'], ),
    sa.PrimaryKeyConstraint('ISIN')
    )
    op.create_table('firds_d',
    sa.Column('ISIN', sa.TEXT(), nullable=True),
    sa.Column('FullName', sa.TEXT(), nullable=True),
    sa.Column('ShortName', sa.TEXT(), nullable=True),
    sa.Column('CFICode', sa.TEXT(), nullable=True),
    sa.Column('Currency', sa.TEXT(), nullable=True),
    sa.Column('ComdtyDerInd', sa.BOOLEAN(), nullable=True),
    sa.Column('IssuerLEI', sa.TEXT(), nullable=True),
    sa.Column('TradingVenueId', sa.TEXT(), nullable=True),
    sa.Column('IssuerReq', sa.BOOLEAN(), nullable=True),
    sa.Column('FirstTradeDate', sa.DATETIME(), nullable=True),
    sa.Column('RlvntCmptntAuthrty', sa.TEXT(), nullable=True),
    sa.Column('RelevantTradingVenue', sa.TEXT(), nullable=True),
    sa.Column('FromDate', sa.DATE(), nullable=True),
    sa.Column('TerminationDate', sa.DATETIME(), nullable=True),
    sa.Column('TotalIssuedNominalAmount', sa.DECIMAL(), nullable=True),
    sa.Column('MaturityDate', sa.DATE(), nullable=True),
    sa.Column('NominalValuePerUnit', sa.DECIMAL(), nullable=True),
    sa.Column('FixedInterestRate', sa.DECIMAL(), nullable=True),
    sa.Column('DebtSeniority', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ISIN')
    )
    op.create_table('equities',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('admission_approval_date', sa.DATE(), nullable=True),
    sa.Column('admission_request_date', sa.DATE(), nullable=True),
    sa.Column('price_multiplier', sa.FLOAT(), nullable=True),
    sa.Column('asset_class', sa.VARCHAR(length=50), nullable=True),
    sa.Column('commodity_product', sa.VARCHAR(length=100), nullable=True),
    sa.Column('energy_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('oil_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('base_product', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sub_product', sa.VARCHAR(length=100), nullable=True),
    sa.Column('additional_sub_product', sa.VARCHAR(length=100), nullable=True),
    sa.Column('metal_type', sa.VARCHAR(), nullable=True),
    sa.Column('precious_metal', sa.VARCHAR(), nullable=True),
    sa.Column('shares_outstanding', sa.FLOAT(), nullable=True),
    sa.Column('market_cap', sa.FLOAT(), nullable=True),
    sa.Column('exchange', sa.VARCHAR(), nullable=True),
    sa.Column('sector', sa.VARCHAR(), nullable=True),
    sa.Column('industry', sa.VARCHAR(), nullable=True),
    sa.Column('underlying_isins', sqlite.JSON(), nullable=True),
    sa.Column('basket_isin', sa.VARCHAR(), nullable=True),
    sa.Column('basket_lei', sa.VARCHAR(), nullable=True),
    sa.Column('underlying_index_isin', sa.VARCHAR(), nullable=True),
    sa.Column('underlying_single_isin', sa.VARCHAR(), nullable=True),
    sa.Column('underlying_single_index_name', sa.VARCHAR(), nullable=True),
    sa.Column('additional_metal_product', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debts',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('total_issued_nominal', sa.FLOAT(), nullable=True),
    sa.Column('maturity_date', sa.DATE(), nullable=True),
    sa.Column('nominal_value_per_unit', sa.FLOAT(), nullable=True),
    sa.Column('fixed_interest_rate', sa.FLOAT(), nullable=True),
    sa.Column('debt_seniority', sa.VARCHAR(length=50), nullable=True),
    sa.Column('coupon_frequency', sa.VARCHAR(length=20), nullable=True),
    sa.Column('credit_rating', sa.VARCHAR(length=10), nullable=True),
    sa.Column('floating_rate_reference', sa.VARCHAR(length=100), nullable=True),
    sa.Column('floating_rate_term_unit', sa.VARCHAR(length=10), nullable=True),
    sa.Column('floating_rate_term_value', sa.FLOAT(), nullable=True),
    sa.Column('floating_rate_basis_points_spread', sa.FLOAT(), nullable=True),
    sa.Column('interest_rate_floating_reference_index', sa.VARCHAR(length=100), nullable=True),
    sa.Column('interest_rate_floating_reference_isin', sa.VARCHAR(length=12), nullable=True),
    sa.Column('underlying_single_isin', sa.VARCHAR(length=12), nullable=True),
    sa.Column('basket_isin', sa.VARCHAR(length=12), nullable=True),
    sa.Column('underlying_index_isin', sa.VARCHAR(length=12), nullable=True),
    sa.Column('underlying_single_index_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('underlying_single_lei', sa.VARCHAR(length=20), nullable=True),
    sa.Column('additional_metal_product', sa.VARCHAR(length=100), nullable=True),
    sa.Column('oil_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('sub_product', sa.VARCHAR(length=100), nullable=True),
    sa.Column('additional_sub_product', sa.VARCHAR(length=100), nullable=True),
    sa.Column('metal_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('precious_metal', sa.VARCHAR(length=50), nullable=True),
    sa.Column('other_commodity_base_product', sa.VARCHAR(length=100), nullable=True),
    sa.Column('underlying_index_name_term_unit', sa.VARCHAR(length=10), nullable=True),
    sa.Column('underlying_index_name_term_value', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firds_e',
    sa.Column('ISIN', sa.TEXT(), nullable=True),
    sa.Column('FullName', sa.TEXT(), nullable=True),
    sa.Column('ShortName', sa.TEXT(), nullable=True),
    sa.Column('CFICode', sa.TEXT(), nullable=True),
    sa.Column('Currency', sa.TEXT(), nullable=True),
    sa.Column('ComdtyDerInd', sa.BOOLEAN(), nullable=True),
    sa.Column('IssuerLEI', sa.TEXT(), nullable=True),
    sa.Column('TradingVenueId', sa.TEXT(), nullable=True),
    sa.Column('IssuerReq', sa.BOOLEAN(), nullable=True),
    sa.Column('FirstTradeDate', sa.DATETIME(), nullable=True),
    sa.Column('UnderlyingInstrm', sa.TEXT(), nullable=True),
    sa.Column('RlvntCmptntAuthrty', sa.TEXT(), nullable=True),
    sa.Column('RelevantTradingVenue', sa.TEXT(), nullable=True),
    sa.Column('FromDate', sa.DATE(), nullable=True),
    sa.Column('TerminationDate', sa.DATETIME(), nullable=True)
    )
    # ### end Alembic commands ###
